version: '3.8' 
services:
  notebooks:
    build: 
      context: data-science/.
      dockerfile: Dockerfile
    container_name: aips-data-science
    ports:
      - "7077:7077" #Spark Master
      - "8080:8080" #Spark Master UI
      - "8081:8081" #Spark Worker UI
      - 8888:8888 # Jupyter Notebook UI 
    depends_on:
      - solr
    networks:
      - solr-data-science
    environment:
      PYSPARK_SUBMIT_ARGS: '--jars /usr/local/spark/lib/spark-solr-3.7.3-shaded.jar pyspark-shell'
      #NB_USER: 'aips'
      #NB_UID: 1010
      #NB_GID: 1020
      #CHOWN_HOME: 'yes'
      #CHOWN_HOME_OPTS: -R    
    volumes:
      - type: bind
        source: "./data-science/notebooks/"
        target: "/tmp/notebooks/"
  solr:
    build:
      context: solr/.
      dockerfile: Dockerfile
    container_name: aips-solr
    hostname: aips-solr
    ports:
      - 8983:8983 
    environment:
      - ZK_HOST=aips-zk:2181
      - SOLR_HOST=aips-solr
    networks:
      - zk-solr
      - solr-data-science
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5.5
    container_name: aips-zk
    hostname: aips-zk
    ports: 
      - 2181:2128
    # - 2181
    networks:
      - zk-solr
      - solr-data-science

  

networks:
  zk-solr:  
  solr-data-science:
